### ISSUE TITLE
How to tie this to a Keyboard Shortcut on MacOs 11.1

### ISSUE THREAD

**Issue by ondohotola** [sven765/externaleditor.sh#1]
Subject says all.

Is there a recipe for dummies?

Thanks, el

**Comment by sven765** [comment]
I have no idea about anything MacOS. Not sure whether the script can even run there. Can anyone help?

**Comment by sven765** [comment]
I am closing this issue because the question is more about MacOS than about this script. Answers are still appreciated, of course!
