### ISSUE TITLE
text with line breaks

### ISSUE THREAD

**Issue by davdent** [sven765/externaleditor.sh#2]
Not sure if this issue is a problem with the script or whether my setup is incorrectly configured. 

1. In Emacs I do M-x server-start. 
2. I go to the Thunderbird window where I want to write a new email. 
3. I press short-cut key to run the script. 
4. A label is added to the window and a new window opens in Emacs. 
5. When I have finished writing my email, I do C-x # and I am asked if I want to save the .eml file. 
6. I say yes. So far so good. 
7. I go back to the TB window and the text is pasted there, but all of the line breaks are gone and so the text is all mushed together, as if it were a single paragraph. 

This also happens when I am replying to an email: all of the text from the preceding email to which I am replying is mushed together, with no line breaks. 

I am running Ubuntu 20.10. Is there something I have incorrectly configured or is this an issue with the script. 

Thanks, Sven, for developing this script!

**Comment by sven765** [comment]
I have no idea. You could, after returning from Emacs, open the temporary file (/tmp/externaleditor-[ID]_saved) in another editor or cat it in a terminal. If the line breaks are in the file, I would guess that it could be a clipboard (or clipboard manager) issue. If the line breaks are missing in the file, I would guess that it's an Emacs configuration thing. Just guessing.

**Comment by davdent** [comment]
The line breaks are included in the temporary file, so it is not an Emacs issue. So, could it be a xclip issue? Or would it more likely be related to xdotools? There seem to be many options for xdotool. Any further thoughts on this? Might I require a delay or a ----clearmodifiers option? Thanks for your help.

**Comment by sven765** [comment]
Another guess: Are you composing HTML email messages? If so: the line breaks have no "meaning" in HTML and are gone. In this case, change the line
`xdotool key ctrl+v # insert clipboard into window`
into
`xdotool key ctrl+shift+v # insert clipboard into window`

In Thunderbird, ctrl+shift+v means "insert without formatting", which seems to work for me.

Unfortunately, I don't think the script can detect whether the Thunderbird composing window is dealing with pure text or HTML, so I do not know how to adapt the script to work with both scenarios.

Please report back, whether that solves the issue. Thanks.

**Comment by psz2036** [comment]
Sorry, but... ctrl-shift+v does not seem to work for me!

Tested "manually" in a Thunderbird compose window: select some text,
ctrl-C to copy, then ctrl-V to paste, or ctrl-shift-V to have no effect
(i.e. nothing happens). I have Thunderbird (78.6.1) on Ubuntu (20.10).

===

A side comment about

> Unfortunately, I don't think the script can detect whether the
> Thunderbird composing window is dealing with pure text or HTML ...

Surely it can, by looking at the contents of the text...

Thanks, Paul

-- 
Paul Szabo       psz@maths.usyd.edu.au       www.maths.usyd.edu.au/u/psz
School of Mathematics and Statistics   University of Sydney    Australia

**Comment by psz2036** [comment]
I wrote:

> ... ctrl-shift+v does not seem to work for me!

I now see that ctrl-shift-V works fine in an "HTML edit" compose window
(when "Compose messages in HTML format" is selected in AccountSettings).
Sorry about the noise.

Cheers, Paul
-- 
Paul Szabo       psz@maths.usyd.edu.au       www.maths.usyd.edu.au/u/psz
School of Mathematics and Statistics   University of Sydney    Australia

**Comment by davdent** [comment]
On my side, I unticked the "compose messages in html format"  in the TB  account settings and the script works perfectly as is. Then I put back the html editing option and changed the script to ctl-shift-v and that works perfectly. So all is well. Thanks so much for this!

**Comment by psz2036** [comment]
I wrote:

> A side comment about
>> Unfortunately, I don't think the script can detect whether the
>> Thunderbird composing window is dealing with pure text or HTML ...
> Surely it can, by looking at the contents of the text...

but I was wrong: you only get the "text" of the message, even though
you may have "Compose messages in HTML format" selected.
(This seems "broken" in TB, no "native" way to edit HTML.)

I guess you would need a combination of the ThunderHTMLedit add-on
https://addons.thunderbird.net/en-US/thunderbird/addon/thunderhtmledit/
(or similar) and this externaleditor.sh.

Cheers, Paul
-- 
Paul Szabo       psz@maths.usyd.edu.au       www.maths.usyd.edu.au/u/psz
School of Mathematics and Statistics   University of Sydney    Australia

**Comment by sven765** [comment]
I have added a configuration option for Thunderbird HTML messages. However, this mainly preserves line breaks and white space. Formatting is generally lost. It might not be a good idea to use this script for formatted text!
