### ISSUE TITLE
Separate config from script

### ISSUE THREAD

**Issue by dbeniamine** [sven765/externaleditor.sh#3]
Hi,

First of all thanks for this script, it's a good replacement for exteditor at least until wayland ....

Anyway I think that it would be a good idea to split the script in two parts

+ `.env.sample` that contains lines 20-45
+ `externaleditor.sh` that sources `.env`

In the readme asks the user to copy `.env.sample => .env` (`.env` is listed in `.gitignore`) so that the configuration changes are ignored by git.

**Comment by sven765** [comment]
Hi @dbeniamine , thank you for your suggestion!

Can you elaborate a bit on why this could be important? I am reluctant to split configuration and execution parts into two files, because it could make the "installation" more difficult and we might loose some users who are not so comfortable with organizing files. Which advantages would outweigh this?

**Comment by dbeniamine** [comment]
Hi,

Currently, If you change the main script and do a `git pull` to get the last version, I will see an error as I have uncommitted modifications :

```
Please commit your changes or stash them before you merge.
Aborting
```

So currently, to get the last version, either we have to copy `externaleditor.sh`, edit the new version and merge it after git pull or we have to do 

```
git stash
git pull
git stash pop
```

And if you made a change in the parmeters part `git  merfetool`

By separating the settings and making people work on a copy of the example setting file you make sure that such merge are never required

**Comment by sven765** [comment]
I see, thanks!

How about if we leave it as a single file and the script checks whether the configuration variables are already set (as environment variables or so) and only sets them if they are not. That way we can have the easy update and just need one file. What do you think?

**Comment by dbeniamine** [comment]
> That way we can have the easy update and just need one file. What do you think?

It solves the git issue but it might makes the key-mapping more complex for some users. Indeed one ight have to set the environment variable in `.profile`. From my point of view it's not a problem but I see how it might make things more complex for some users.

Are you concerned by the idea of having two files or the possible retro-compatibility issue due to this change ?

**Comment by sven765** [comment]
Thanks, that made it clearer to me, and again thanks for the suggestion!

I have separated configuration from the script now, so I will close this issue. Hope the way I did it serves your needs. If not, please let me know!

**Comment by sven765** [comment]
Issue solved by separating the configuration from the script.

**Comment by dbeniamine** [comment]
> Thanks, that made it clearer to me, and again thanks for the suggestion!
> 
> I have separated configuration from the script now, so I will close this issue. Hope the way I did it serves your needs. If not, please let me know!

It's perfect, thanks again, I'm happy to be able to edit my mails from Vim again !
