### ISSUE TITLE
text not pushed back from emacsclient

### ISSUE THREAD

**Issue by scfrank-pri** [sven765/externaleditor.sh#4]
First of all, thanks for taking action - I was waiting for this for a long time.
The problem I experienced: From emacsclient, I could not push back the text to the TB message window, even with focus etc. 
emacsclient finishes OK after C-x #, but then nothing happens in the TB message window. It still says: "_!ExternalEditorIsEditingThis!_"  (TB 78.7.1 ubuntu, gnu emacs 26.3)

On another note, you may want to add to your Readme, that after creating the keyboard shortcut one has to make sure it can be run: in ubuntu: Open nautilus ->     Files menu -> behaviour tab ->     Run executable text files when they are opened
I found this hint here: https://askubuntu.com/questions/299052/how-to-execute-sh-script-from-a-desktop-shortcut

**Comment by sven765** [comment]
That's weird. When you press C-x # in Emacs, does the TB editor window come to front (front of all other windows) and get focus (i.e. the cursor is in the TB editor window)?

**Comment by scfrank-pri** [comment]
no, the TB editor window does not get focus - even that it hat focus when I started the script. 
I thought this may depend on the different workspaces I use for TB and emacs, but even putting them on the same workspace does not improve. (it actually works fine if I had chosen emacs instead of emacsclient -- but that would not make a lot of sense for me)

**Comment by sven765** [comment]
Thanks for your answer. I am only guessing that it has to do with the window manager or its configuration. (I use emacsclient in the xfce desktop environment and - with my configuration - it works.) When using emacs (new frame) after you close emacs the thunderbird window may be in front again (if the order of the windows has not changed), whereas when using emacsclient, the emacs frame is not closed and thunderbird needs to be brought to front in order for the script to interact with it.

You could try the following: Copy line 132:
  xdotool windowactivate "${windowid}" # raise window
right under (or above) line 118:
  if xdotool windowfocus "${windowid}" 2>/dev/null; then # only if the original window can get focus

This would raise (bring to front) the thunderbird window earlier and maybe "help" the window manager interact with it.

If you try this, please report back whether this helps! Thanks.

**Comment by scfrank-pri** [comment]
I tried, no improvement. I noticed the following: When I have started a new emacs, then everything works as expected - but only 1 time. Afterwards, the text is not pushed back - but the TB message window gets the focus. So, the problem seems to be that the text is not copied back (except for the 1st time). Hope this helps. Thanks for your efforts.

**Comment by scfrank-pri** [comment]
Next update after a few trials with the original script (i.e. without your modifications suggested at line 118): 
When I close the emacs buffer with C-x #, the TB message window gets focus, but _!ExternalEditorIsEditingThis!_ is not replaced by the text. I have to yank it in with C-v, i.e. the text is in the clipboard, and have to remove _!ExternalEditorIsEditingThis!_ manually from the buffer. I talked to a colleague to test the script, for him it worked as expected. No idea what is not working for me. I just noticed that the variable emailclientwindowtitle is obviously not used in my emacsclient.

**Comment by sven765** [comment]
Well, here is another wild guess: Maybe your window manager needs some time to activate the window and the script executes the following steps too fast? You could try adding "sleep .4" (= wait for 0.4 seconds) below line 118. (If it works, you can probably reduce the time.)

Any difference?

**Comment by scfrank-pri** [comment]
I think it is now more or less OK :-) - for longer text it works fine. Thanks a lot for your work!

**Comment by martinp26** [comment]
I seem to have the same problem with xfce.  I could solve it with a 0.5s sleep before the if.
